stages:
  data_load:
    cmd: python3 src/data_load.py
    deps:
      - src/data_load.py
    outs:
      - data/input.csv
      - data/output.csv

  data_preprocess:
    cmd: python3 src/data_preprocess.py
    deps:
      - src/data_preprocess.py
      - data/input.csv
      - data/output.csv
    params:
      - data_preprocess.test_size
      - data_preprocess.random_state
    outs:
      - data/train.csv
      - data/test.csv
      - data/train_labels.csv
      - data/test_labels.csv
      - data/model/scaler.joblib

  train:
    cmd: python3 src/train.py
    deps:
      - src/train.py
      - data/train.csv
      - data/train_labels.csv
    params:
      - train.kernel
      - train.gamma
      - train.c
    outs:
      - data/model/model.joblib

  test:
    cmd: python3 src/test.py
    deps:
      - src/test.py
      - data/model/model.joblib
      - data/test.csv
      - data/test_labels.csv
    metrics:
      - metrics/model_metrics.json